### ISSUE TITLE
smile.amazon.com doesn't work

### ISSUE THREAD

**Issue by nullbasis** [amazon-alternatives/extension#77]
The add-on doesn't work if I'm on an Amazon Smile page, which is ironically the only halfway-ethical way to shop on Amazon.

**Comment by adriantombu** [comment]
Hey @nullbasis, thanks for opening this issue, I'll fix it this week :)

**Comment by adriantombu** [comment]
Hey @nullbasis it should be fixed by this PR https://github.com/amazon-alternatives/extension/pull/80 and available in a few hours in the stores
