### ISSUE TITLE
Add-on doesn't work for pre-orders.

### ISSUE THREAD

**Issue by nullbasis** [amazon-alternatives/extension#78]
If I click on "pre-order this item" for an item that isn't out yet, it just takes me to the usual Amazon checkout page.

**Comment by adriantombu** [comment]
I'll check this too this week, could you provide me with the link of a page with a pre-order item ?

**Comment by nullbasis** [comment]
Sure. https://www.amazon.com/Visitor-Animorphs-Graphix-2/dp/1338538373

**Comment by adriantombu** [comment]
Hey @nullbasis it should be fixed by this PR https://github.com/amazon-alternatives/extension/pull/80 and available in a few hours in the stores
